# This workflow will get triggered when commit is pushed in an branch in the repository.
# We're using Dockerhub access token instead of username, password for security purpose (recommended by docker) to push the image.
# In a real env, it would be good to use docker layer caching depending on the pricing.

name: learn-github-actions

on:
  push:
    branches:
      - sbaghel_phase1

env:
  DOCKERHUB_USERNAME:   ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPO}}

jobs:
  build-and-push:
    name: "Build and Push the docker image to DockerHub"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v3
      - name: "Login to Dockerhub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}          
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: "Build the docker image"
        # Using latest tag for simplicity
        run: docker image build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest .
      - name: "Push the docker image to the DockerHub repo"
        run: docker image push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest
